#!/usr/bin/sh

autoload -U colors zsh/terminfo
colors

autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git hg
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:git*' formats "%{${fg[cyan]}%}[%{${fg[white]}%}%s%{${fg[cyan]}%}][%{${fg[green]}%}%r/%S%%{${fg[cyan]}%}][%{${fg[blue]}%}%b%{${fg[yellow]}%}%m%u%c%{${fg[cyan]}%}]%{$reset_color%}"


# Highlight the user name when logged in as root.
if [[ "${USER}" == "root" ]]; then
	userStyle="%F{red}";
else
	userStyle="%F{166}";
fi;

# Highlight the hostname when connected via SSH.
if [[ "${SSH_TTY}" ]]; then
	hostStyle="%B%F{red}";
else
	hostStyle="%F{yellow}";
fi;

PROMPT='${userStyle}%n %F{white}at ${hostStyle}%m %F{white}in %B%F{green}%~%f%b 
%(!.#.$) '

RPROMPT=$'${vcs_info_msg_0_}'